version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=DEV
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=damian
      - DB_PASS=damiancxliew
      - DB_NAME=web-forum
      - DB_SSLMODE=disable
    volumes:
      - .:/app
    networks:
      - app_network
    restart: always

  # Example of a database service if required for local testing
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: damian
      POSTGRES_PASSWORD: damiancxliew
      POSTGRES_DB: web-forum
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  db-data:
