version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=DEV
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=damian
      - DB_PASS=damiancxliew
      - DB_SSLMODE=disable
      - DB_NAME=web-forum
    networks:
      - app_network
    restart: always
    depends_on:
      db:
        condition: service_healthy

  # Example of a database service if required for local testing
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: damian
      POSTGRES_PASSWORD: damiancxliew
      POSTGRES_DB: web-forum
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U damian -d web-forum"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  app_network:
    driver: bridge

volumes:
  db-data:
